'use client';

import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Award, Calendar } from 'lucide-react';

export default function StaffPerformancePage() {
  const [period, setPeriod] = useState('today');
  const [customDate, setCustomDate] = useState(new Date().toISOString().split('T')[0]);
  const [reportData, setReportData] = useState<any>(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => { fetchReport(); }, [period, customDate]);

  const fetchReport = async () => {
    setIsLoading(true);
    const now = new Date();
    let from = '', to = now.toISOString().split('T')[0];

    switch (period) {
      case 'today':
        from = to;
        break;
      case 'week':
        const weekAgo = new Date(now);
        weekAgo.setDate(weekAgo.getDate() - 7);
        from = weekAgo.toISOString().split('T')[0];
        break;
      case 'month':
        from = `${now.getFullYear()}-${(now.getMonth() + 1).toString().padStart(2, '0')}-01`;
        break;
      case 'custom':
        from = customDate;
        to = customDate;
        break;
    }

    try {
      const res = await fetch(`/api/reports/sales?from=${from}&to=${to}`);
      const data = await res.json();
      setReportData(data);
    } catch { } finally { setIsLoading(false); }
  };

  return (
    <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4 }}>
      <div className="flex items-center justify-between mb-6">
        <div className="section-header" style={{ marginBottom: 0 }}>
          <div className="section-icon" style={{ background: 'linear-gradient(135deg, #EFF6FF, #DBEAFE)' }}>
            <Award className="w-5 h-5" style={{ color: '#2563EB' }} />
          </div>
          <div>
            <h1 className="section-title">Staff Performance</h1>
            <p className="section-subtitle">Track tables, orders, and revenue generated by your team</p>
          </div>
        </div>

        {/* Period Selector */}
        <div className="flex gap-1 p-1 rounded-lg" style={{ backgroundColor: '#F9FAFB' }}>
          {[
            { id: 'today', label: 'Today' },
            { id: 'week', label: 'This Week' },
            { id: 'month', label: 'This Month' },
          ].map(p => (
            <button
              key={p.id}
              onClick={() => setPeriod(p.id)}
              className="px-3 py-1.5 rounded-md text-xs font-medium transition-all cursor-pointer"
              style={{
                backgroundColor: period === p.id ? '#FFFFFF' : 'transparent',
                color: period === p.id ? '#1A1A1A' : '#6B7280',
                boxShadow: period === p.id ? '0 1px 2px rgba(0,0,0,0.06)' : 'none',
              }}
            >
              {p.label}
            </button>
          ))}
          <div className="flex items-center ml-2 border-l border-gray-200 pl-2">
            <input 
              type="date" 
              value={customDate} 
              onChange={(e) => { setCustomDate(e.target.value); setPeriod('custom'); }} 
              className="px-2 py-1.5 rounded-md text-xs font-medium border border-gray-200 bg-white text-gray-700 outline-none focus:border-indigo-500 cursor-pointer"
            />
          </div>
        </div>
      </div>

      {/* Staff Performance Table */}
      <div className="premium-card" style={{ overflow: 'hidden' }}>
        <table className="w-full text-sm">
          <thead>
            <tr style={{ backgroundColor: '#F9FAFB', borderBottom: '1px solid #E5E7EB' }}>
              <th className="text-left px-5 py-3 text-xs font-semibold uppercase tracking-wider" style={{ color: '#6B7280' }}>Staff Member</th>
              <th className="text-center px-5 py-3 text-xs font-semibold uppercase tracking-wider" style={{ color: '#6B7280' }}>Tables Handled</th>
              <th className="text-center px-5 py-3 text-xs font-semibold uppercase tracking-wider" style={{ color: '#6B7280' }}>Orders Processed</th>
              <th className="text-right px-5 py-3 text-xs font-semibold uppercase tracking-wider" style={{ color: '#6B7280' }}>Total Revenue Generated</th>
            </tr>
          </thead>
          <tbody>
            {isLoading ? (
              <tr>
                <td colSpan={4} className="px-5 py-12 text-center text-sm" style={{ color: '#9CA3AF' }}>
                  Loading staff performance data...
                </td>
              </tr>
            ) : (reportData?.staff_performance || []).map((staff: any, i: number) => (
              <tr key={`${staff.name}-${i}`} style={{ borderBottom: '1px solid #F3F4F6' }}>
                <td className="px-5 py-4">
                  <div className="font-semibold text-sm" style={{ color: '#1A1A1A' }}>{staff.name}</div>
                  <div className="text-[10px] uppercase font-bold tracking-wider mt-0.5" style={{ color: '#6B7280' }}>{staff.role}</div>
                </td>
                <td className="px-5 py-4 text-center font-medium" style={{ fontFamily: 'var(--font-mono)', color: '#374151', fontSize: '15px' }}>{staff.tablesHandled}</td>
                <td className="px-5 py-4 text-center font-medium" style={{ fontFamily: 'var(--font-mono)', color: '#374151', fontSize: '15px' }}>{staff.ordersHandled}</td>
                <td className="px-5 py-4 text-right font-bold text-emerald-600" style={{ fontFamily: 'var(--font-mono)', fontSize: '15px' }}>₹{staff.revenue?.toLocaleString('en-IN')}</td>
              </tr>
            ))}
            {!isLoading && (!reportData?.staff_performance || reportData.staff_performance.length === 0) && (
              <tr><td colSpan={4} className="px-5 py-12 text-center text-sm" style={{ color: '#9CA3AF' }}>No staff performance data for this period</td></tr>
            )}
          </tbody>
        </table>
      </div>
    </motion.div>
  );
}
